# 配置DataSource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chattom?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 13507557103wlt
    initialSize: 5
    maxActive: 100
    minIdle: 3
    maxWait: 50000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: team.cats.pojo
  global-config:
    id-type: 1
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true

    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

wechat:
  appid: 
  secret: 
